version: '3.9'

services:
  db:
    container_name: vape_db_container
    image: postgres:alpine3.18
    environment:
      POSTGRES_DB: vape_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      vape_net:
        ipv4_address: 10.6.0.3
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s


  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      vape_net:
        ipv4_address: 10.6.0.6

networks:
  vape_net:
    name: vape_net
    ipam:
      config:
        - subnet: 10.6.0.0/16
          gateway: 10.6.0.1
